### ISSUE TITLE
【social buzz】jioPhone

### ISSUE THREAD

**Issue by chenyukun** [chenyukun/grow#2]

**Comment by Longxin-newsdog** [comment]
直接套uc模板

**Comment by chenyukun** [comment]
短信里的链接换成：http://bit.ly/free_jio_phone

**Comment by chenyukun** [comment]
http://jiophone.new-free-offer.in/step4.html， @zhangshaohua1 翻译成hindi

**Comment by Longxin-newsdog** [comment]
短信：
[Jio] Enjoy free jio, enjoy happy life! Free Jio Phone Giving Out! Only 3402 free phones left! click bit.ly/free_jio_phone

**Comment by zhangshaohua1** [comment]
Jio Mobile Sale
Register Now by App
You Need to Install our Partner App newsDog to prove you are not a Robot
Hurry Up!! Only Limited Stocks are Avaliable
After install please open app atleast 5 Mintues to Confirm your Details
Install App & Enter Your Delivery Address

जियो मोबाइल सेल
ऐप द्वारा अब रजिस्टर करें
आपको हमारे पार्टनर ऐप न्यूजडोग को इंस्टॉल करना होगा, ताकि हमें मालुम है कि आप एक रोबोट नहीं हैं
जल्दी करो!! स्टॉक सीमित हैं
इंस्टॉल करने के बाद अपने विवरण की पुष्टि करने के लिए कृपया ऐप को कम से कम 5 मिनट इस्तेमाल करें
ऐप इंस्टॉल करें & अपना डिलीवरी पता दर्ज करें
