### ISSUE TITLE
【social buzz】paytm风险检测

### ISSUE THREAD

**Issue by chenyukun** [chenyukun/grow#3]
输入你的paytm账号和姓名，查看是否存在安全风险。然后80%几率查出安全风险来，检测到已经被黑客入侵，“你是xx，你的号码是xxx，你的账号已经被破解，黑客将在2天后从你的账户扣除20000卢比。”paytm提供免费的安全加密服务，但我们要验证你是否为机器人。请你下载这个App，然后将第一篇文章的链接分享到自己的WhatsApp群里，然后截图上传给我们，验证后，我们将临时加密你的账号，黑客将无法入侵。

**Comment by Longxin-newsdog** [comment]
**网页：**
第一页：
输入你的paytm账号和姓名，查看是否存在安全风险。
提交
第二页
80%几率查出安全风险来，检测到已经被黑客入侵，“你是xx，你的号码是xxx，你的账号已经被破解，黑客将在2天后从你的账户扣除20000卢比。”
按钮【立即免费紧急加密】
第三页
paytm提供免费的安全加密服务，但我们要验证你是否为机器人。
请你下载这个paytm合作方的App，然后将第一篇文章的链接分享到自己的WhatsApp群里，然后截图上传给我们，我们的人工智能服务器将立刻对图片进行分析。若成功，将紧急加密，保证你不受损失。

第四页
上传图片后，我们的工程师正在紧急加密你的账号，请耐心等待。为了保持手机内数据的完整性，期间请不要卸载手机内的任何App，任何卸载行为都将导致加密时效。

paytm黑客正在蔓延，赶快把这个链接发送到你的朋友那里，帮助他们免受损失！
按钮【立即分享给朋友】
按钮【发短信给他们】

**WhatsApp信息：**

印度安全保密部门昨天晚上1点发布紧急消息，印度已经有20万人的paytm账号被入侵，黑客已经从20万账号上盗取了40亿卢比的金额，印度全国警方已经开始行动。paytm已经推出了账号加密方式，快点来加固账号，防止账号被盗，资金损失！link

**短信：**
印度安全保密部门紧急消息，20万人paytm被盗损失40亿卢比，paytm紧急安全加密服务，快点来保护自己的财产！
